<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>SqliteDemo.DataAdapter</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.*" />
    <PackageReference Include="NReco.Data" Version="1.2.*" />
  </ItemGroup>

  <ItemGroup>  
    <MySourceFiles Include="$(MSBuildProjectDirectory)/../DemoData/northwind.db"/>  
  </ItemGroup>
  <Target Name="CopySqliteDbFile" BeforeTargets="Build">
	<Copy SourceFiles="@(MySourceFiles)"  
          DestinationFolder="$(MSBuildProjectDirectory)"/>  
  </Target>   
  
</Project>
