version: 1.0.{build}
os: Visual Studio 2022
configuration: Release
platform: Any CPU

branches:
  only:
  - master

skip_tags: true

install:
- cmd: dotnet restore src\NReco.Data.sln

build_script:
- cmd: dotnet build src\NReco.Data --configuration Release
- cmd: dotnet build src\NReco.Data.Tests --configuration Release

test_script:
- cmd: dotnet test src\NReco.Data.Tests\NReco.Data.Tests.csproj --configuration Release